import 'package:get/get.dart';

import '../../module/items_model.dart';

class ItemsController extends GetxController {
  List<String> grids = ["101", "102", "201", "202", "301", "302", "401", "402"];

  List<ItemsModel> drinkItems = [
    ItemsModel(
      id: '001',
      name: 'Coca-Cola Classic',
      price: 1.25,
      availableQuantity: '100',
      itemChannelNumber: '101',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '002',
      name: 'Pepsi',
      price: 1.20,
      availableQuantity: '120',
      itemChannelNumber: '101',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '003',
      name: 'Sprite',
      price: 1.10,
      availableQuantity: '150',
      itemChannelNumber: '101',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '004',
      name: 'Mountain Dew',
      price: 1.15,
      availableQuantity: '90',
      itemChannelNumber: '102',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '005',
      name: 'Dr Pepper',
      price: 1.30,
      availableQuantity: '80',
      itemChannelNumber: '102',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '006',
      name: 'Fanta Orange',
      price: 1.25,
      availableQuantity: '110',
      itemChannelNumber: '102',
      itemCategory: 'Soft Drinks',
    ),
    ItemsModel(
      id: '007',
      name: 'Red Bull',
      price: 2.00,
      availableQuantity: '200',
      itemChannelNumber: '201',
      itemCategory: 'Energy Drinks',
    ),
    ItemsModel(
      id: '008',
      name: 'Monster Energy',
      price: 2.10,
      availableQuantity: '180',
      itemChannelNumber: '202',
      itemCategory: 'Energy Drinks',
    ),
    ItemsModel(
      id: '009',
      name: 'Gatorade',
      price: 1.50,
      availableQuantity: '150',
      itemChannelNumber: '202',
      itemCategory: 'Sports Drinks',
    ),
    ItemsModel(
      id: '010',
      name: 'Powerade',
      price: 1.50,
      availableQuantity: '160',
      itemChannelNumber: '301',
      itemCategory: 'Sports Drinks',
    ),
    ItemsModel(
      id: '011',
      name: 'Lipton Iced Tea',
      price: 1.45,
      availableQuantity: '140',
      itemChannelNumber: '301',
      itemCategory: 'Tea Drinks',
    ),
    ItemsModel(
      id: '012',
      name: 'Snapple Peach Tea',
      price: 1.35,
      availableQuantity: '130',
      itemChannelNumber: '302',
      itemCategory: 'Tea Drinks',
    ),
    ItemsModel(
      id: '013',
      name: 'Arizona Green Tea',
      price: 0.99,
      availableQuantity: '180',
      itemChannelNumber: '401',
      itemCategory: 'Tea Drinks',
    ),
    ItemsModel(
      id: '014',
      name: 'Starbucks Frappuccino',
      price: 2.99,
      availableQuantity: '100',
      itemChannelNumber: '402',
      itemCategory: 'Coffee Drinks',
    ),
    ItemsModel(
      id: '015',
      name: 'Nescafe Classic',
      price: 1.99,
      availableQuantity: '120',
      itemChannelNumber: '401',
      itemCategory: 'Coffee Drinks',
    ),
    ItemsModel(
      id: '016',
      name: 'Pure Leaf Unsweetened Tea',
      price: 1.75,
      availableQuantity: '95',
      itemChannelNumber: '401',
      itemCategory: 'Tea Drinks',
    ),
    ItemsModel(
      id: '017',
      name: 'Vitamin Water',
      price: 1.80,
      availableQuantity: '200',
      itemChannelNumber: '401',
      itemCategory: 'Enhanced Water',
    ),
    ItemsModel(
      id: '018',
      name: 'Perrier',
      price: 2.50,
      availableQuantity: '180',
      itemChannelNumber: '402',
      itemCategory: 'Sparkling Water',
    ),
    ItemsModel(
      id: '019',
      name: 'LaCroix Sparkling Water',
      price: 1.00,
      availableQuantity: '170',
      itemChannelNumber: '202',
      itemCategory: 'Sparkling Water',
    ),
    ItemsModel(
      id: '020',
      name: 'Aquafina Water',
      price: 0.90,
      availableQuantity: '300',
      itemChannelNumber: '201',
      itemCategory: 'Water',
    ),
  ];
}
